package com.github.yuanmomo.mybatis.generator.test.bean;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class DynamicTable implements Serializable {

    public static DynamicTable init(int intValue, long longValue, String stringValue, String textValue) {
        DynamicTable dynamicTable = new DynamicTable();
        dynamicTable.setIntValue(intValue);
        dynamicTable.setLongValue(longValue);
        dynamicTable.setStringValue(stringValue);
        dynamicTable.setTextValue(textValue);
        return dynamicTable;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg_table.int_value
     *
     * @mbg.generated
     */
    private Integer intValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg_table.long_value
     *
     * @mbg.generated
     */
    private Long longValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg_table.string_value
     *
     * @mbg.generated
     */
    private String stringValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg_table.text_value
     *
     * @mbg.generated
     */
    private String textValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    private String dynamicTableName;
}
