package com.github.yuanmomo.mybatis.generator.test.bean;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.Builder;

@ToString
@Builder
@NoArgsConstructor
@Data
@EqualsAndHashCode
public class MultiKeyTable implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multi_key_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multi_key_table.int_value
     *
     * @mbg.generated
     */
    private Integer intValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multi_key_table.long_value
     *
     * @mbg.generated
     */
    private Long longValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multi_key_table.string_value
     *
     * @mbg.generated
     */
    private String stringValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multi_key_table.text_value
     *
     * @mbg.generated
     */
    private String textValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
