package com.github.yuanmomo.mybatis.generator.test.mapper;

import org.apache.ibatis.jdbc.SQL;
import com.github.yuanmomo.mybatis.generator.test.bean.BlobTable;

public class BlobTableSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,hash,detail";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    public String insertSelective(BlobTable record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("blob_table");
        if (record.getHash() != null) {
            sql.VALUES("hash", "#{hash,jdbcType=VARCHAR}");
        }
        if (record.getDetail() != null) {
            sql.VALUES("detail", "#{detail,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(BlobTable record) {
        SQL sql = new SQL();
        sql.UPDATE("blob_table");
        if (record.getHash() != null) {
            sql.SET("hash = #{hash,jdbcType=VARCHAR}");
        }
        if (record.getDetail() != null) {
            sql.SET("detail = #{detail,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }
}
