package com.github.yuanmomo.mybatis.generator.test.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import com.github.yuanmomo.mybatis.generator.test.bean.BlobTable;
import org.apache.ibatis.annotations.SelectKey;

public interface BlobTableMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    @Delete({ "delete from blob_table", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    @InsertProvider(type = BlobTableSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insertSelective(BlobTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    @Select({ "select", "id, hash, detail", "from blob_table", "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true), @Result(column = "hash", property = "hash", jdbcType = JdbcType.VARCHAR), @Result(column = "detail", property = "detail", jdbcType = JdbcType.LONGVARCHAR) })
    BlobTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    @UpdateProvider(type = BlobTableSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BlobTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blob_table
     *
     * @mbg.generated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    @Insert({ "<script>", "insert into blob_table (hash, ", "detail)", "values<foreach collection=\"list\" item=\"detail\" index=\"index\" separator=\",\">(#{detail.hash,jdbcType=VARCHAR}, ", "#{detail.detail,jdbcType=LONGVARCHAR})</foreach></script>" })
    int batchInsert(java.util.List<BlobTable> list);
}
