package com.github.yuanmomo.mybatis.generator.test.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import com.github.yuanmomo.mybatis.generator.test.bean.DynamicTable;

public interface DynamicTableMapper {

    @Select({ "select count(id) from ${tableName}" })
    int count(@Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    @Delete({ "delete from ${tableName}", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(@Param("tableName") String tableName, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    @InsertProvider(type = DynamicTableSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    @Select({ "select", "id, int_value, long_value, string_value, text_value", "from ${tableName}", "where id = #{id,jdbcType=BIGINT}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true), @Result(column = "int_value", property = "intValue", jdbcType = JdbcType.INTEGER), @Result(column = "long_value", property = "longValue", jdbcType = JdbcType.BIGINT), @Result(column = "string_value", property = "stringValue", jdbcType = JdbcType.VARCHAR), @Result(column = "text_value", property = "textValue", jdbcType = JdbcType.LONGVARCHAR) })
    DynamicTable selectByPrimaryKey(@Param("tableName") String tableName, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    @UpdateProvider(type = DynamicTableSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(@Param("tableName") String tableName, @Param("record") DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    @Options(useGeneratedKeys = true, keyProperty = "list.id", keyColumn = "id")
    @Insert({ "<script>", "insert into ${tableName} (int_value, ", "long_value, string_value, ", "text_value)", "values<foreach collection=\"list\" item=\"detail\" index=\"index\" separator=\",\">(#{detail.intValue,jdbcType=INTEGER}, ", "#{detail.longValue,jdbcType=BIGINT}, #{detail.stringValue,jdbcType=VARCHAR}, ", "#{detail.textValue,jdbcType=LONGVARCHAR})</foreach></script>" })
    int batchInsert(@Param("tableName") String tableName, @Param("list") java.util.List<DynamicTable> list);
}
