package com.github.yuanmomo.mybatis.generator.test.mapper;

import com.github.yuanmomo.mybatis.generator.test.bean.MbgTable;
import org.apache.ibatis.jdbc.SQL;

public class MbgTableSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,int_value,long_value,string_value,text_value";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    public String insertSelective(MbgTable record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("mbg_table");
        if (record.getIntValue() != null) {
            sql.VALUES("int_value", "#{intValue,jdbcType=INTEGER}");
        }
        if (record.getLongValue() != null) {
            sql.VALUES("long_value", "#{longValue,jdbcType=BIGINT}");
        }
        if (record.getStringValue() != null) {
            sql.VALUES("string_value", "#{stringValue,jdbcType=VARCHAR}");
        }
        if (record.getTextValue() != null) {
            sql.VALUES("text_value", "#{textValue,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbg_table
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MbgTable record) {
        SQL sql = new SQL();
        sql.UPDATE("mbg_table");
        if (record.getIntValue() != null) {
            sql.SET("int_value = #{intValue,jdbcType=INTEGER}");
        }
        if (record.getLongValue() != null) {
            sql.SET("long_value = #{longValue,jdbcType=BIGINT}");
        }
        if (record.getStringValue() != null) {
            sql.SET("string_value = #{stringValue,jdbcType=VARCHAR}");
        }
        if (record.getTextValue() != null) {
            sql.SET("text_value = #{textValue,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        return sql.toString();
    }
}
