package com.github.yuanmomo.mybatis.generator.test.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import com.github.yuanmomo.mybatis.generator.test.bean.MultiKeyTable;
import org.apache.ibatis.annotations.Options;

public interface MultiKeyTableMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    @Delete({ "delete from multi_key_table", "where id = #{id,jdbcType=BIGINT}", "and int_value = #{intValue,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(@Param("id") Long id, @Param("intValue") Integer intValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    @InsertProvider(type = MultiKeyTableSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(MultiKeyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    @Select({ "select", "id, int_value, long_value, string_value, text_value", "from multi_key_table", "where id = #{id,jdbcType=BIGINT}", "and int_value = #{intValue,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true), @Result(column = "int_value", property = "intValue", jdbcType = JdbcType.INTEGER, id = true), @Result(column = "long_value", property = "longValue", jdbcType = JdbcType.BIGINT), @Result(column = "string_value", property = "stringValue", jdbcType = JdbcType.VARCHAR), @Result(column = "text_value", property = "textValue", jdbcType = JdbcType.LONGVARCHAR) })
    MultiKeyTable selectByPrimaryKey(@Param("id") Long id, @Param("intValue") Integer intValue);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    @UpdateProvider(type = MultiKeyTableSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MultiKeyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multi_key_table
     *
     * @mbg.generated
     */
    @Insert({ "<script>", "insert into multi_key_table (int_value, ", "long_value, string_value, ", "text_value)", "values<foreach collection=\"list\" item=\"detail\" index=\"index\" separator=\",\">(#{detail.intValue,jdbcType=INTEGER}, ", "#{detail.longValue,jdbcType=BIGINT}, #{detail.stringValue,jdbcType=VARCHAR}, ", "#{detail.textValue,jdbcType=LONGVARCHAR})</foreach></script>" })
    int batchInsert(java.util.List<MultiKeyTable> list);
}
